version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "miniconda3-3.12-24.9"

sphinx:
   configuration: docs/conf.py
   fail_on_warning: true

conda:
  environment: devtools/conda-envs/docs_env.yaml

python:
  install:
    - method: pip
      path: .
