from typing import Literal, Union

from openff.units.units import Quantity
from openmm import unit as openmm_unit

def openmm_unit_to_string(input_unit: openmm_unit.Unit) -> str: ...
def string_to_openmm_unit(unit_string: str) -> openmm_unit.Unit: ...
def from_openmm(openmm_quantity: openmm_unit.Quantity) -> Quantity: ...
def to_openmm(quantity: Quantity) -> openmm_unit.Quantity: ...
def ensure_quantity(
    unknown_quantity: Union[Quantity, "openmm_unit.Quantity"],
    type_to_ensure: Literal["openmm", "openff"],
) -> Union[Quantity, "openmm_unit.Quantity"]: ...
