class ParameterIOHandler:
    def __init__(self) -> None: ...
    def parse_file(self, file_path) -> None: ...
    def parse_string(self, data) -> None: ...
    def to_file(self, file_path, smirnoff_data) -> None: ...
    def to_string(self, smirnoff_data) -> None: ...

class XMLParameterIOHandler(ParameterIOHandler):
    def parse_file(self, source): ...
    def parse_string(self, data): ...
    def to_file(self, file_path, smirnoff_data) -> None: ...
    def to_string(self, smirnoff_data): ...
