from _typeshed import Incomplete

class ToolkitWrapper:
    @classmethod
    def requires_toolkit(cls): ...
    @property
    def toolkit_name(self): ...
    @property
    def toolkit_installation_instructions(self): ...
    @property
    def toolkit_file_read_formats(self): ...
    @property
    def toolkit_file_write_formats(self): ...
    @classmethod
    def is_available(cls): ...
    @property
    def toolkit_version(self): ...
    def from_file(self, file_path, file_format, allow_undefined_stereo: bool = ...): ...
    def from_file_obj(
        self,
        file_obj,
        file_format,
        allow_undefined_stereo: bool = ...,
        _cls: Incomplete | None = ...,
    ): ...
