from typing import DefaultDict, Dict, List, Optional, Tuple

from openmm.app import Topology as OpenMMTopology

class OpenFFToolkitException(Exception):
    msg: str
    def __init__(self, msg) -> None: ...

class IncompatibleUnitError(OpenFFToolkitException): ...
class MissingPackageError(OpenFFToolkitException): ...
class ToolkitUnavailableException(OpenFFToolkitException): ...
class LicenseError(ToolkitUnavailableException): ...
class InvalidToolkitError(OpenFFToolkitException): ...
class InvalidToolkitRegistryError(OpenFFToolkitException): ...
class UndefinedStereochemistryError(OpenFFToolkitException): ...
class GAFFAtomTypeWarning(RuntimeWarning): ...
class ChargeMethodUnavailableError(OpenFFToolkitException): ...
class IncorrectNumConformersError(OpenFFToolkitException): ...
class IncorrectNumConformersWarning(Warning): ...
class ChargeCalculationError(OpenFFToolkitException): ...
class ConformerGenerationError(OpenFFToolkitException): ...
class InvalidIUPACNameError(OpenFFToolkitException): ...
class AntechamberNotFoundError(OpenFFToolkitException): ...
class SMILESParseError(OpenFFToolkitException, ValueError): ...
class RadicalsNotSupportedError(OpenFFToolkitException): ...
class InvalidConformerError(OpenFFToolkitException): ...
class SmilesParsingError(OpenFFToolkitException): ...
class NotAttachedToMoleculeError(OpenFFToolkitException): ...
class NotInTopologyError(OpenFFToolkitException): ...
class AtomNotInTopologyError(NotInTopologyError): ...
class MoleculeNotInTopologyError(NotInTopologyError): ...
class BondNotInTopologyError(NotInTopologyError): ...
class InvalidAtomMetadataError(OpenFFToolkitException): ...
class DuplicateUniqueMoleculeError(OpenFFToolkitException): ...
class NotBondedError(OpenFFToolkitException): ...
class InvalidBondOrderError(OpenFFToolkitException): ...
class InvalidBoxVectorsError(OpenFFToolkitException): ...
class InvalidPeriodicityError(OpenFFToolkitException): ...
class MissingUniqueMoleculesError(OpenFFToolkitException): ...
class SMIRKSMismatchError(OpenFFToolkitException): ...
class SMIRKSParsingError(OpenFFToolkitException): ...
class ParameterHandlerRegistrationError(OpenFFToolkitException): ...
class SMIRNOFFVersionError(OpenFFToolkitException): ...
class SMIRNOFFAromaticityError(OpenFFToolkitException): ...
class InvalidAromaticityModelError(OpenFFToolkitException, ValueError): ...
class SMIRNOFFParseError(OpenFFToolkitException): ...
class PartialChargeVirtualSitesError(OpenFFToolkitException): ...
class SMIRNOFFSpecError(OpenFFToolkitException): ...
class SMIRNOFFSpecUnimplementedError(OpenFFToolkitException): ...
class FractionalBondOrderInterpolationMethodUnsupportedError(
    OpenFFToolkitException
): ...
class NotEnoughPointsForInterpolationError(OpenFFToolkitException): ...
class IncompatibleParameterError(OpenFFToolkitException): ...
class UnassignedValenceParameterException(OpenFFToolkitException): ...
class UnassignedBondParameterException(UnassignedValenceParameterException): ...
class UnassignedAngleParameterException(UnassignedValenceParameterException): ...
class UnassignedProperTorsionParameterException(
    UnassignedValenceParameterException
): ...
class UnassignedMoleculeChargeException(OpenFFToolkitException): ...
class DuplicateParameterError(OpenFFToolkitException): ...
class ParameterLookupError(OpenFFToolkitException): ...
class DuplicateVirtualSiteTypeException(OpenFFToolkitException): ...
class CallbackRegistrationError(OpenFFToolkitException, TypeError): ...
class HierarchySchemeWithIteratorNameAlreadyRegisteredException(
    OpenFFToolkitException
): ...
class HierarchySchemeNotFoundException(OpenFFToolkitException): ...
class MissingIndexedAttributeError(
    OpenFFToolkitException, IndexError, KeyError, AttributeError
): ...
class MissingPartialChargesError(OpenFFToolkitException, ValueError): ...
class UnsupportedMoleculeConversionError(OpenFFToolkitException): ...
class InconsistentStereochemistryError(OpenFFToolkitException): ...
class UnsupportedFileTypeError(OpenFFToolkitException): ...
class MultipleMoleculesInPDBError(OpenFFToolkitException): ...
class WrongShapeError(OpenFFToolkitException): ...
