"""
A collection of classes representing data stored by a storage backend.
"""
from propertyestimator.attributes import (
    UNDEFINED,
    MergeableAttributeClass,
    InequalityMergeBehaviour,
    InputAttribute,
)
from propertyestimator.properties import PropertyPhase
from propertyestimator.substances import Substance
from propertyestimator.thermodynamics import ThermodynamicState


class BaseStoredData(MergeableAttributeClass):
    """A base representation of cached data to be stored by
    a storage backend.

    The expectation is that stored data will exist in storage
    as two parts:

        1) A JSON serialized representation of this class (or
           a subclass), which contains lightweight information
           such as the state and composition of the system. Any
           larger pieces of data, such as coordinates or
           trajectories, should be referenced by this class as
           a filename.

        2) A directory like structure (either directly a directory,
           or some NetCDF like compressed archive) of ancillary
           files which do not easily lend themselves to be
           serialized within a JSON object, whose files are referenced
           by name by the data object.
    """

    substance = InputAttribute(
        docstring="A description of the composition of the stored system.",
        type_hint=Substance,
        default_value=UNDEFINED,
    )
    thermodynamic_state = InputAttribute(
        docstring="The state at which the data was collected.",
        type_hint=ThermodynamicState,
        default_value=UNDEFINED,
    )
    property_phase = InputAttribute(
        docstring="The phase of the system (e.g. liquid, gas).",
        type_hint=PropertyPhase,
        default_value=UNDEFINED
    )

    source_calculation_id = InputAttribute(
        docstring="The server id of the calculation which yielded this data.",
        type_hint=str,
        default_value=UNDEFINED,
    )

    provenance = InputAttribute(
        docstring="Provenance information about how this data was generated.",
        type_hint=dict,
        default_value=UNDEFINED,
    )

    force_field_id = InputAttribute(
        docstring="The id of the force field parameters used to generate the data.",
        type_hint=str,
        default_value=UNDEFINED,
    )


class StoredSimulationData(BaseStoredData):
    """A representation of data which has been cached
    from a single previous simulation.

    Notes
    -----
    The ancillary directory which stores larger information such
    as trajectories should be of the form:

    .. code-block::

        |--- data_object.json
        |--- data_directory
             |--- coordinate_file_name.pdb
             |--- trajectory_file_name.dcd
             |--- statistics_file_name.csv
    """

    coordinate_file_name = InputAttribute(
        docstring="The name of a coordinate file which encodes the "
        "topology information of the system.",
        type_hint=str,
        default_value=UNDEFINED,
    )
    trajectory_file_name = InputAttribute(
        docstring="The name of a .dcd trajectory file containing "
        "configurations generated by the simulation.",
        type_hint=str,
        default_value=UNDEFINED,
    )

    statistics_file_name = InputAttribute(
        docstring="The name of a `StatisticsArray` csv file, containing "
        "statistics generated by the simulation.",
        type_hint=str,
        default_value=UNDEFINED,
    )
    statistical_inefficiency = InputAttribute(
        docstring="The statistical inefficiency of the collected data.",
        type_hint=float,
        default_value=UNDEFINED,
        merge_behavior=InequalityMergeBehaviour.SmallestValue,
    )

    total_number_of_molecules = InputAttribute(
        docstring="The total number of molecules in the system.",
        type_hint=int,
        default_value=UNDEFINED,
    )
